appName: myhelmapp

namespace: default

configmap:
  name: helmappconfigmapv1.1
  data:
    CUSTOM_HEADER: This app was deployed with defaul value and namespace!!!

image:
  name: devopsjourney1/mywebapp
  tag: latest
